### ISSUE TITLE
mute adapter trimming

### ISSUE THREAD

**Issue by ShaokangZhang** [haotianteng/Chiron#101]
Hi Haotian,
Very impressive tool.
Are there any approaches to make Chiron not trim the adapters and keep the whole sequence?
Regards,
Shaokang

**Comment by haotianteng** [comment]
Chiron didn't trim adapter if the adapter is present in the raw signal, however I think for DNA signal the adapter is not in the raw signal. For RNA basecall, please try this tool: BoostNano which can identify the adapter and the polyA tail directly from the raw signal.
