### ISSUE TITLE
How to make the evaluation to work on multiple cores

### ISSUE THREAD

**Issue by drdivine** [haotianteng/Chiron#105]
**Describe the requested feature**
It would be great if I have multiple GPUs that the evaluation i.e. `chiron call` would work on mulitple GPUs. Any advice for making this work?
**Additional context**

**Comment by haotianteng** [comment]
Currently, multi GPU support is not implemented, but you can split the reads and call Chiron multiple times, in each call, use the following command to choose the GPU, for example, choose the first GPU:
`export CUDA_VISIBLE_DEVICES=0`
and then run chiron using `chiron call`
