### ISSUE TITLE
Chiron file depreciated?

### ISSUE THREAD

**Issue by KFeye** [haotianteng/Chiron#108]
**Describe the bug**
Started training my dataset from ONT, had the following error:

**To Reproduce**
python chiron/utils/raw.py --input ~/Desktop/YellowFast5Pass/ --output ~/Desktop/YellowBaseCalled/ --mode dna
WARNING:tensorflow:From chiron/utils/raw.py:53: The name tf.gfile.Walk is deprecated. Please use tf.io.gfile.walk instead.

Traceback (most recent call last):
  File "chiron/utils/raw.py", line 169, in <module>
    run(args)
  File "chiron/utils/raw.py", line 148, in run
    run_list(dirs,output_folder)
  File "chiron/utils/raw.py", line 111, in run_list
    extract(root_folder,output_folder)
  File "chiron/utils/raw.py", line 70, in extract
    total = total_errors)
TypeError: update() got an unexpected keyword argument 'title'
(base) Drs-iMac:Chiron dr.kristinafeyewaseen$ 

**Screenshots**
Provided code

**Environment (please complete the following information):**
 - OS: iOS macOS Mojave v 10.14.6
 - CPU 4 Ghz intel core i7
 - Chiron Version Recent download from tutorial 
 - Tensorflow Version Recent download from tutorial 
 - Python Version 3.7.6
 - Other related packages version

**Comment by haotianteng** [comment]
Need to install older version of Tensorflow:
``` bash
pip install tensorflow==1.15
```
