### ISSUE TITLE
Failed to start the call

### ISSUE THREAD

**Issue by Eric-from-TW** [haotianteng/Chiron#109]
Hi, 
I am new in bioinformatics. There is a issue I encounter while chiron call. 'AttributeError: 'module' object has no attribute '__version__' '. could anyone help me about this? Thanks.
![Screenshot from 2021-05-12 18-00-44](https://user-images.githubusercontent.com/58993427/117957346-91cdc480-b34c-11eb-849e-660eeb7f8c31.png)

**Comment by haotianteng** [comment]
better to install from pip:
```bash
pip install chiron
chiron call
```
