### ISSUE TITLE
Biopython incompatible while installing Chiron using PIP

### ISSUE THREAD

**Issue by Saranya-nanobiophotonics-lab** [haotianteng/Chiron#112]
**Describe the bug**
 I had created a virtual environment with python version 2.7. But, when I try to install Chiron using pip command, I get the following error
 "ERROR: Command errored out with exit status 1:
     command: /home/saranya/work/TelN/analysis/virtual_environment/chiron/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Dw45yE/biopython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Dw45yE/biopython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_fxEjm
         cwd: /tmp/pip-install-Dw45yE/biopython/
    Complete output (1 lines):
    **Biopython requires Python 3.6 or later. Python 2.7 detected.**
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Screenshots**
![Screenshot 2022-05-10 at 3 31 02 PM](https://user-images.githubusercontent.com/97092812/167603954-5ce8061d-64cf-4aaf-bed3-9c70b424612c.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - GPU [GeForce GT 610, Driver version: 390.147]
 - Chiron Version [e.g. 0.4.1]
 - Tensorflow Version [e.g. 1.15 - gpu as recommended in the chrion GitHub information: ]
 - Python Version [: 2.7]
 - Other related packages version

**Comment by haotianteng** [comment]
conda create -n YOUR_ENVIRONMENT_NAME python=3.6
conda activate YOUR_ENVIRONMENT_NAME
pip install chiron
