### ISSUE TITLE
chunks consensus

### ISSUE THREAD

**Issue by F0nz0** [haotianteng/Chiron#120]
Hi and thank you very much for your very interesting paper and tool.
I would really appretiate to receive some additional information about Chiron.
More in detail, I'm facing with a similar task and I'm trying to find inside your code how you merged overlapping chunks to produce the final basecalled reads, but I haven't been able to do that. 
Could you indicate the script performing this task (finding consensus sequence between contiguous chunks of outputs produced during the basecalling step) ?

Thank you very much in advance
Best Regards.

**Comment by haotianteng** [comment]
It's in this scripit: [chiron/utils/easy_assembler.py](https://github.com/haotianteng/Chiron/blob/56a5362b1cdb2b7ec6c2bae0a062300fb208b306/chiron/utils/easy_assembler.py)

There are several different assembly methods depending on the jump ratio, the default one is a simple sticking method, i.e. simply concatenate the chunks.
