### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by huangnengCSU** [haotianteng/Chiron#13]
Hi hao,
when I read the codes, I feel a little confused about ".label" format of the training data. Whether each line in the label file is the bases of the whole sequence or the kmer ? If you don't mind, can you give me an example of training data. Thank you.

**Comment by mbhall88** [comment]
Hi @huangnengCSU . There is an example of what that file should look like at https://github.com/haotianteng/Chiron#training
Let us know if that doesn't work for you.

**Comment by huangnengCSU** [comment]
thank you
issue closed
