### ISSUE TITLE
NotFoundError when calling

### ISSUE THREAD

**Issue by pcjedi** [haotianteng/Chiron#20]
I tried to call without further training but received a not Found Error. Extraction works fine, afterwards Chiron loads the checkpoint but can't find certain stuff in it.
pip version works fine. 
Maybe checkpoints aren't mobile between systems or has the code changed till checkpoint?
Full Error Message in File attached:
[chiron_error.txt](https://github.com/haotianteng/Chiron/files/1734900/chiron_error.txt)

**Comment by haotianteng** [comment]
Please install the release version (v0.3), the mainstream is still under development.

**Comment by haotianteng** [comment]
You have to use
