### ISSUE TITLE
Deprecate chiron_rcnn_train?

### ISSUE THREAD

**Issue by mbhall88** [haotianteng/Chiron#21]
Note at the top of [`chiron_rcnn_train.py`](https://github.com/haotianteng/Chiron/blob/clean_code/chiron/chiron_rcnn_train.py) saying it is going to deprecated. I cannot find any usage of this module in any other modules. Should I delete it?

**Comment by haotianteng** [comment]
This is the script used for training, it is one of the main function in entry.py.(Chiron train will call this module), and it is going to be replaced by chiron_train.py. Yes delete it as the Chiron_train.py module has been tested.
