### ISSUE TITLE
Mutable Default Argument in CNN module

### ISSUE THREAD

**Issue by mbhall88** [haotianteng/Chiron#22]
In function `conv_layer` the parameter `stride` on [this](https://github.com/haotianteng/Chiron/blob/7bb07f58aafaed5acf8b00362b36b81dbab55431/chiron/cnn.py#L17) line has a mutable default argument `[1, 1, 1, 1]`. Is this intentional?   

[This article](http://docs.python-guide.org/en/latest/writing/gotchas/) explains why this is a problem with the following example:

```py
def append_to(element, to=[]):
    to.append(element)
    return to

my_list = append_to(12)
print(my_list)
#[12]
my_other_list = append_to(42)
print(my_other_list)
#[12, 42]
```

> A new list is created once when the function is defined, and the same list is used in each successive call.
Python’s default arguments are evaluated once when the function is defined, not each time the function is called (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.  

If this is the functionality you want (i.e continual adding elements into that initial list) then that's fine, we can leave it as is.   
But if you want the list to be redefined everytime the function is called, I would suggest changing it to this:

```py
def conv_layer(indata, ksize, padding, training, name, dilate=1,
               strides=None, bias_term=False, active=True,
               BN=True, active_function='relu'):
    if strides is None:
        strides = [1, 1, 1, 1]
```

**Comment by haotianteng** [comment]
This is not the same case, the problem you talked about is due to the use
of append.
Please send e-mail direclty to me instead of using the Issue.

Thanks
Teng
