### ISSUE TITLE
Chiron base calling error using new model file

### ISSUE THREAD

**Issue by varma-k** [haotianteng/Chiron#28]
ok got it "Fixed it by modifying chiron_eval.py file". thanks

Hi,

I am using TensorFlow version 1.1.0 and Chiron in a virtual env

I have successfully trained Chiron on our own nanopore sequencing data (RNA) and facing an error when trying to do the base-calling using trained model. 

I am getting following error when I do the base calling using my trained model.

I am guessing this is a possible error due to change in TensorFlow version and model file output format.
or am I missing something else

Please suggest a workaround. 

Following is the complete error log.

NotFoundError (see above for traceback): Key BDLSTM_rnn/cell_2/bidirectional_rnn/bw/lstm_cell/biases not found in checkpoint
	 [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]
	 [[Node: save/RestoreV2_43/_35 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_250_save/RestoreV2_43", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

 
Any help will be greatly appreciated
Raja

**Comment by varma-k** [comment]
ok fixed it

**Comment by haotianteng** [comment]
Check out the current developing branch clean_code, it should work with Tensorflow > 1.3.0 now.

**Comment by ardakdemir** [comment]
@varma-k  How did you fix this issue?
