### ISSUE TITLE
training and call use different model?

### ISSUE THREAD

**Issue by huangnengCSU** [haotianteng/Chiron#33]
I find when do model training, the program will call the function run() in file chiron_rcnn_train.py. And when do base calling, the program will call the function run() in file chiron_eval.py. But the structure of the two neural nets in two files seem to be different. In chiron_rcnn_train, there are no RNN layers, rather there are RNN layers in chiron_eval.

**Comment by haotianteng** [comment]
fixed

**Comment by haotianteng** [comment]
The chiron_rcnn_train.py is going to be deprecated, we optimized the input pipeline with a file queue input, so I would recommend using utils/file_batch.py to generate a file batch first and then use chiron_train.py to train a model.
