### ISSUE TITLE
Illumina Data Availability

### ISSUE THREAD

**Issue by emdyess** [haotianteng/Chiron#37]
Hi Haotian, 

Nice work on Chiron.  It looks very promising.  I was able to obtain the E.coli fast5 files from genomicsresearch.org, but I do not see the corresponding MiSeq data.  It also does not seem to be on Genbank yet.  Is it possible to post the MiSeq data for E.coli on the genomicsresearch.org site?  Do you happen to know when it might be available on Genbank?

Thanks!

**Comment by haotianteng** [comment]
Assembly of Illumina reads (Reference) now is provided in according folder.

**Comment by emdyess** [comment]
Hi Haotian,

Thanks for posting the Illumina assembly.  However, I was actually hoping to get the raw fastq files.  Is it possible to make those available on the same site?

Thanks!

**Comment by haotianteng** [comment]
Sorry, the raw fastq Illumina reads are not available for now, because the E.coli dataset is provided by our collaborators, and their work is still in progress.
