### ISSUE TITLE
TensorFlow Version

### ISSUE THREAD

**Issue by qianlou** [haotianteng/Chiron#52]
Hi, Haotianteng.

Can you tell me the version of tensorflow you used to run Chiron? Or is it  no matter about the versions of tensorflow? Based on my previous experience, the version of tensorflow is very important because different versions of tensorflow have different APIs. If the version of my tensorflow does not match yours, maybe I can't install your Chiron program.

**Comment by qianlou** [comment]
Sorry. I have found that you have answered this question. Thanks.

**Comment by qianlou** [comment]
Does this program support Python 3.6?

**Comment by haotianteng** [comment]
Hi I test with tf 1.3 1.4 1.6 and they all work. So I think tf>1.30 will do
the job, older version will not work as they change the definition of model
protobuf since tf1.3.

Thanks
Teng

**Comment by haotianteng** [comment]
Yes, the current version is py2/3 compatible.

**Comment by qianlou** [comment]
Hi teng,

Thanks for your reply. I just tested the example data under the CPU version. But I met NotFound errors. I found others met this error previously. Do I must use Version 0.3? 
Thanks.
Qian

**Comment by qianlou** [comment]
Hi Teng,
I used a command like this : python chiron/entry.py call -i chiron/example_data/ -o ./  >> test.txt
Then I got the following outputs attached on the test.txt 
[test.txt](https://github.com/haotianteng/Chiron/files/2007480/test.txt)

**Comment by haotianteng** [comment]
I have uploaded the configuration file, can you update and try again?

**Comment by qianlou** [comment]
Thanks again, Teng. Now I run "python chiron/entry.py call .." this command successfully. I will try to run Chiron on my GPU and train a new model. During the future process, maybe I also need to discuss with you. So please let me say thank you in advance.

Best regards,
Qian

**Comment by qianlou** [comment]
Thank you so much Teng! I get up now and will try it right now. After that, I will tell you the feedback. 

Qian
