### ISSUE TITLE
Parallel run & architecture warnings 

### ISSUE THREAD

**Issue by apredeus** [haotianteng/Chiron#56]
Hello, 

I was wondering if one can run basecalling in parallel? What are the expected run times? I'm calling a 300k read 2Gb Nanopore run and it's still not done after 24h. 

I'm also getting some warnings after installing chiron with pip - would this matter for basecalling, or is it only relevant for training? Thanks! 

> tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

**Comment by haotianteng** [comment]
You can specify the threads used by --thread argument. Are you running it on a cluster or locally? You should see a progress bar that will give you an approximate finish time.

And what is your current setting?

The warning is generated by Tensorflow, not by Chiron, it indicates that your CPU has the indicated structure that could be used if you install Tensorflow from source.

**Comment by apredeus** [comment]
I'm running it on the cluster. I don't think we have access to GPU, but I will check. What is the minimum requirements for Chiron GPU usage? Could you use it with a simple powerful videocard? 

> The warning is generated by Tensorflow, not by Chiron, it indicates that your CPU has the indicated structure that could be used if you install Tensorflow from source.

So it should not matter for the basecalling process, just for training, right? 

Thanks again!

**Comment by haotianteng** [comment]
A Nvidia GPU is necessary, as it is required by Tensorflow

It's just a warning, so no worry about it :)
