### ISSUE TITLE
chiron-0.3.tar.gz and Pypi have invalid setup.py

### ISSUE THREAD

**Issue by genomematt** [haotianteng/Chiron#57]
File "/private/var/folders/3_/7gn1zhl111q5c1cx1dvr2pt00000gp/T/pip-install-tjw5y3nx/chiron/setup.py", line 10
        """
          ^
    SyntaxError: invalid syntax

Ok in current master, but your pip install instruction fail due to this error.

**Comment by haotianteng** [comment]
Chiron 0.4 has been released.
