### ISSUE TITLE
Did you train a BNLSTM model?

### ISSUE THREAD

**Issue by qianlou** [haotianteng/Chiron#58]
Hi, Haotian. Now the default model is based on LSTM model. Did you train a BNLSTM model? If so, can you share with me? Training a new model in 20000 steps needs so much time and when I trained a new model, it interrupted at 7340 steps maybe because of my hardware problem.

**Comment by haotianteng** [comment]
No I don't have a batch normalized LSTM, you can use the module to train one if you like. BNLSTM is slower than LSTM with current implementation.

**Comment by haotianteng** [comment]
No I don't have a batch normalized LSTM, you can use the module to train one if you like. BNLSTM is slower than LSTM with current implementation.
