### ISSUE TITLE
ImportError: No module named chiron

### ISSUE THREAD

**Issue by pcjedi** [haotianteng/Chiron#61]
when calling "python entry.py" the Error "ImportError: No module named chiron" occurs. 

the line "from chiron import chiron_eval" raises this. Changing it to "import chiron_eval" fixes this, but raises the same error in many other lines.

**Comment by pcjedi** [comment]
with chiron also installed via pip, this error does not occur. But I don't think that this is the desired behavior.

**Comment by haotianteng** [comment]
Have a read of README.md and follow the install instruction if you want to install from source, but to solve your problem export PYTHONPATH=where you installed chiron
