### ISSUE TITLE
RNA model - no output

### ISSUE THREAD

**Issue by jnaitsaada** [haotianteng/Chiron#65]
Hi,

I tried to use Chiron with the RNA model, but all output files are empty. It works fine with the DNA model though.

I looked into the source code, and in the evaluation function, it seems that the prediction from the CTC decoder is empty. I don't know where the problem comes from. Any idea ?

Thank you

**Comment by haotianteng** [comment]
The RNA model is still under development, I will release an update this month.

Thank you 
Teng

**Comment by haotianteng** [comment]
A new RNA model has been updated.

**Comment by JMiguelRamirez** [comment]
Hi, 
I am trying to use Chiron with the RNA model and it doesn't work, even though it works completely fine with DNA. Is the RNA version not completely implemented yet?

Thank you very much and sorry for the inconvenience,
