### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by etheleon** [haotianteng/Chiron#7]
Hi, 

I'm trying to retrain using chiron_cnn_train.py

I see the read_raw_data_sets function gives two output in the following line https://github.com/haotianteng/Chiron/blob/master/chiron/chiron_cnn_train.py#L36

However, when I looked at the function defined in `chiron_input.py` it only returns train and not the validation. 

Any ideas?

**Comment by haotianteng** [comment]
Check out the new version, now only one training data set is return.
Now the validation dataset can be created by creating a separate data reader.
