### ISSUE TITLE
question about trainning

### ISSUE THREAD

**Issue by qhli1** [haotianteng/Chiron#70]
**About nanoraw re-squiggle**
I use this command line:
nanoraw genome_resquiggle /home/human/f5/  /home/human/fa/1.fasta  --bwa-mem-executable  /home/qhli/anaconda2/envs/tensorflow-gpu/bin/bwa  --overwrite     
It is right or not?  This command would not report any errors. 

**chiron_ file_batch.py**
I use this command line:
python  /chiron/utils/file_batch.py  --input /home/qhli/human/f5 --output /home/qhli/human/process --length 400 --mode dna    
the result:
File batch transfer completed, 0 batches have been processed
2 files scussesfully read, 0 files failed.
                    
But when i use the result of the re_ squiggled fast5, it would show no batch, which result in the result: ValueError: string_input_producer requires a non-null input tensor when I use the Chiron_train.py.

Therefore, could you please give me some advice? Thank you very much!

**Comment by haotianteng** [comment]
Nanoraw has now transferred to Tombo, I have updated the README.md.
