### ISSUE TITLE
problems about accuarcies

### ISSUE THREAD

**Issue by qhli1** [haotianteng/Chiron#71]
Dear Hao Tianteng,
I want to ask you two reasons about the training and the model have been trained. 
 
1. I use your DNA model to test. The testing function that I use is chiron_eval.py. And the testing data is provided by you: Lambda_eval_0001.signal and Lambda_eval_0001.label. But the identity rate is only 0.02%. After that, I use other data to test, some could reach 60%. But the overall performance is not satisfactory and can not reach the accuracy mentioned in the paper. Therefore, I want to ask the reasons.

2. I try to train the new model. The dataset is pass.tar.gz provided by you. when I use the first method:chiron_rcnn_train.py, the loss decreases from 500 to 4 and it dose not seem to decrease. But the training model is not accurate. After that, I use the chiron_train.py. The loss decreases to about 90 and dose not decrease again. 

Thank you for your patience to read my issues. I really look forward to your reply.

Bests,
Li Qiuhui

**Comment by haotianteng** [comment]
Hi qhli1,
there is no way a identity rate can go to 0.02% even the basecaller just output all A. Can you provide the output fastq file?
