### ISSUE TITLE
base call failed after training

### ISSUE THREAD

**Issue by lfaino** [haotianteng/Chiron#72]
**Describe the bug**
Dear Developer,
i`m trying to train chiron on some data for my model organism. this is a fungi and the characteristics is that there is not methylation at all in the genome

**To Reproduce**
these are the command that I used to create the model and run the model

`tombo resquiggle  fast5/ Fus.contigs.polished.methilated.SRR1609157.sorted.vcf.fasta --processes 4 --num-most-common-errors 5 --dna --overwrite`
`python3 /usr/local/lib/python3.5/dist-packages/chiron/utils/raw.py --input fast5/ --output b`

`python3 /usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py --data_dir chiron_output --log_dir modelFus --model_name Fus -n 20000 &> logTraining`

`python3 /usr/local/lib/python3.5/dist-packages/chiron/entry.py call -i fast5/ -o chiron_call/ -m Fus`

However, after that the last step generated about 40k reads, I tried to map the reads on the genome and to my surprise only 3 reads where mapped to the genome out of 40k. I think that something went wrong somewhere. Can you place help me?

**Environment (please complete the following information):**
 - OS: 22~16.04.1-Ubuntu SMP
 - GPU Tesla P100-PC
 - Chiron Version 0.4.2
 - Tensorflow Version 1.12.0rc0
 - Python Version python 3.5

**Additional context**
I used the latest version of tombo to resquiggle  the reads

**Comment by haotianteng** [comment]
Can you share your model Fus configure?
Please use the same configuration as DNA_default to train a DNA model.

**Comment by lfaino** [comment]
here you are... 
[logTraining.txt](https://github.com/haotianteng/Chiron/files/2524271/logTraining.txt)


about the command with the configuration, you mean a command like this:
`python3 /usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py --data_dir chiron_output --log_dir modelFus --model_name Fus  -t 1e-2 -b 300 --retrain --configure modelFus/Fus_retrin/model.json`

**Comment by haotianteng** [comment]
--retrain will automatically choose the same configuration in the DNA_default folder.

I see, the training process is overfitted, can you get more reads? 10X more reads (500 -> 5000) would be necessary. You can check if it's overfitted by setting a validation dataset by -v when training.

For example:
separate your fast5 files into two folders: fast5_train fast5_valid
run raw.py twice to get a train.tfrecords and valid.tfrecords
```
python3 /usr/local/lib/python3.5/dist-packages/chiron/utils/raw.py --input fast5_train/ --output <OUTPUT_FOLDER> -f train.tfrecords
python3 /usr/local/lib/python3.5/dist-packages/chiron/utils/raw.py --input fast5_valid/ --output <OUTPUT_FOLDER> -f valid.tfrecords
python chiron_rcnn_train.py -i chiron_output -f train.tfrecords -v valid.tfrecords -o modelFus --model_name Fus_retrain -t 1e-2 -b 300 --retrain
```

**Comment by lfaino** [comment]
Hi, 
I do not get this work

I run:

`python3 /usr/local/lib/python3.5/dist-packages/chiron/utils/raw.py -i fast5/20180927_0800_ale8/ -o tfrecord/ -f train.tfrecords &> log.train.txt &`

`python3 /usr/local/lib/python3.5/dist-packages/chiron/utils/raw.py -i fast5/20180927_1139_Fv10027_2/ -o tfrecord/ -f valid.tfrecords &> log.valid.txt &`

`python3 /usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py --data_dir tfrecord --log_dir modelFus --model_name Fus_retrain -t 1e-2 -b 300 --retrain --configure modelFus/Fus_retrin/model.json -f train.tfrecords -v valid.tfrecords
`

and i get this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py", line 183, in <module>
    run(args)
  File "/usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py", line 142, in run
    train()
  File "/usr/local/lib/python3.5/dist-packages/chiron/chiron_rcnn_train.py", line 49, in train
    raise ValueError("Model Json file has not been found in model log directory")
ValueError: Model Json file has not been found in model log directory
`

the structure of my folders are:
./
./Fus.contigs.polished.methilated.SRR1609157.sorted.vcf.fasta.fai
./Fv10027.allNanopore.fastq
./log.train.txt
./tfrecord
./tfrecord/train.tfrecords
./tfrecord/valid.tfrecords
./modelFus
./modelFus/Fus_retrin
./modelFus/Fus_retrin/checkpoint
./modelFus/Fus_retrin/model.json
./modelFus/Fus_retrin/model.ckpt-209071.index
./modelFus/Fus_retrin/model.ckpt-209071.data-00000-of-00001
./modelFus/Fus_retrin/model.ckpt-209071.meta
./fast5
./.fast5.RawGenomeCorrected_000.tombo.index
./Fus.contigs.polished.methilated.SRR1609157.sorted.vcf.fasta
./log.valid.txt

**Comment by lfaino** [comment]
Hi, 
I finally got it work. It was a mistake in the folder name.

Howver, I have another problem. I can not set 
`python3 /usr/local/lib/python3.5/dist-packages/chiron/entry.py call` 
to work with my trained folder ` /usr/local/lib/python3.5/dist-packages/chiron/model/Fus_retrain/`. 
It always uses the DNA_default as you can see from:
`['call', '-i', 'fast5/20180927_0800_ale8/fast5/pass/0/', '-o', 'test', '--model', '/usr/local/lib/python3.5/dist-packages/chiron/model/Fus_retrain/']
model_default_path /usr/local/lib/python3.5/dist-packages/chiron/model/DNA_default
Subdirectory processing:: 0it [00:00, ?it/s]`

the full command  that i use is:
`python3 /usr/local/lib/python3.5/dist-packages/chiron/entry.py call -i fast5/20180927_0800_ale8/fast5/pass/0/ -o test --model /usr/local/lib/python3.5/dist-packages/chiron/model/Fus_retrain/`

**Comment by haotianteng** [comment]
edit /usr/local/lib/python3.5/dist-packages/chiron/model/Fus_retrain/checkpoint

You will see something like:
model_checkpoint_path: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38291"
all_model_checkpoint_paths: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38251"
all_model_checkpoint_paths: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38261"
all_model_checkpoint_paths: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38271"
all_model_checkpoint_paths: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38281"
all_model_checkpoint_paths: "/shares/coin/haotian.teng/deepBNS/data/IVT/IVT_unmodified/log//rna1_model1/model.ckpt-38291"

Change the first line to the relative path and delete other lines:
model_checkpoint_path: "model.ckpt-38291"

This should make it work.

**Comment by haotianteng** [comment]
Have you got it solved? I will close this issue at first.
