### ISSUE TITLE
Attention decoder implementation

### ISSUE THREAD

**Issue by nbathreya** [haotianteng/Chiron#76]
So, when you implemented attention decoder, you just inserted in the attention_loss as prediction error?

Another question, in attention_loss function, you describe "label_len:[batch_size] label length, the <end> symbol is included." Do we have to include "end" symbol at the end of each label batch as we pass to this command?

Is it possible to provide a training code with attention mechanism used? I would like to make sure I use the chiron model with attention right. (I want to see how much of a difference there is with attention and non-attention mechanism and see mathematically what is causing that). This would help me GREATLY!

Plus I face this error:

WARNING:tensorflow:From /home/conjugacy/Downloads/project/utils/attention.py:87: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
Traceback (most recent call last):
  File "train_test.py", line 104, in <module>
    error = prediction(logits, seq_length, y)
  File "train_test.py", line 82, in prediction
    error = attention_loss(logits,seq_length,label,FLAGS.batch_size)
  File "/home/conjugacy/Downloads/project/utils/attention.py", line 26, in attention_loss
    logits,attention_list=attention_decoder(inputs,seq_len,cell,max_label_len=max_seq_len,label=label_dense)
  File "/home/conjugacy/Downloads/project/utils/attention.py", line 183, in attention_decoder
    y_hat = tf.one_hot(label[:,index],depth=5,on_value=1.0,off_value=0.0,axis=-1)
TypeError: 'SparseTensor' object is not subscriptable

_Originally posted by @nbathreya in https://github.com/haotianteng/Chiron/issues/75#issuecomment-444753713_

**Comment by haotianteng** [comment]
That's just a warning about a future depreciation, and currently, attention decoder is no longer under the development plan. Contribution is welcomed.

As for your question, yes, if you want to implement attention decoder, an "end" symbol is necessary, but as the read is super long and could not feed completely into the RAM during training(Tensorflow will flatten the RNN cell during training), so usually we have to split each read into chunks to train, but directly adding 'end' at each label segment will causing the basecaller unable to basecall a complete sequence during inference. One way is to add an artificial blank signal into each chunk while adding 'end' symbol in each chunk's label segment, so it make the basecaller still basecall a complete sequence in inference and also able to train.
