### ISSUE TITLE
run entry.py call report error

### ISSUE THREAD

**Issue by huangnengCSU** [haotianteng/Chiron#78]
**Describe the bug**

**To Reproduce**
Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - GPU [GTX 1080]
 - Chiron Version [0.4.2]
 - Tensorflow Version [1.8.0-gpu]
 - Python Version [2.7]
 - Other related packages version

**Additional context**

['call', '-i', 'chiron/example_data/DNA/', '-o', 'exp', '-m', '/home/tiger/codes/Chiron/chiron/model/DNA_default']
('model_default_path', '/home/tiger/codes/Chiron/chiron/model/DNA_default')
Subdirectory processing:: 0it [00:00, ?it/s]                                                                                                                                                               INFO:root:chiron/example_data/DNA/read5.fast5 has no reference.                                                                                                                        | 0/5 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "chiron/entry.py", line 99, in <module>
    main()
  File "chiron/entry.py", line 91, in main
    args.func(args)
  File "chiron/entry.py", line 24, in evaluation
    extract(FLAGS)
  File "/home/tiger/codes/Chiron/chiron/utils/extract_sig_ref.py", line 77, in extract
    if (FLAGS.test_number is not None) and (count >=FLAGS.test_number):
AttributeError: 'Namespace' object has no attribute 'test_number'

**Comment by haotianteng** [comment]
fixed, thx
