### ISSUE TITLE
Test data available in the paper Chiron

### ISSUE THREAD

**Issue by qianlou** [haotianteng/Chiron#81]
**Can't download the test data including human, Ecoli. Just have training data**

**Hello, I have dowloaded the training data from the link (https://data.genomicsresearch.org/Projects/train_set_all/). But I could not download any test data even from the supporting link at your chiron paper.

**Comment by haotianteng** [comment]
Please check out here:
http://gigadb.org/dataset/100425
eval.tar.gz and train.tar.gz are the training dataset and evaluation dataset.
And also in the above link, the 3 full datasets are available(Human, Lambda and S10). mix_hel is training dataset. I have just tested the link, they are all good. Don't know why you can't get it.
