### ISSUE TITLE
Parameter inconsistency in `read_raw_data_sets()`

### ISSUE THREAD

**Issue by franrodalg** [haotianteng/Chiron#82]
Hi,
The call to `read_raw_data_sets` in `train_test.py`: 

https://github.com/haotianteng/Chiron/blob/70c14bccd3316bd1e84619961b8c883139354d1c/chiron/train_test.py#L61

seems to be inconsistent with the signature of the function in `chiron_input.py`:

https://github.com/haotianteng/Chiron/blob/70c14bccd3316bd1e84619961b8c883139354d1c/chiron/chiron_input.py#L415

This causes a `TypeError` exception to be thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: read_raw_data_sets() got an unexpected keyword argument 'valid_reads_num'
```

Note that also the positional arguments don't match.

I haven't tried using `chiron_cnn_train.py`, but I suspect it will also cause an issue there:

https://github.com/haotianteng/Chiron/blob/b013416def86a06fb54fd66bf481fb536b1db284/chiron/chiron_cnn_train.py#L57-L59

Cheers,
Fran

**Comment by haotianteng** [comment]
Hi, please don't use chiron_cnn_train.py and chiron_train_test.py these two are scripts no longer used.
Use chiron_rcnn_train.py instead.
I will remove those two scripts.
