### ISSUE TITLE
Add version info

### ISSUE THREAD

**Issue by tarunaaggarwal** [haotianteng/Chiron#84]
**Describe the requested feature**
Can you please add the version info in the `help` outputs when folks run `chiron call -h`? At the moment, it is not very intuitive how to find which Chiron version is being used.

**Comment by haotianteng** [comment]
Okay, no problem.
For now:
```python
import chiron
print(chiron.__version__)
```
should do the job

**Comment by haotianteng** [comment]
version argument added.
python entry.py -v
now show the version number. This works for version > 0.5
