### ISSUE TITLE
Basecalling with DNA_default

### ISSUE THREAD

**Issue by ardakdemir** [haotianteng/Chiron#90]
I am trying to do basecalling using the DNA_default folder provided.
I get the following error also raised previously when running a new trained model. Yet in my case I am just trying to use the already provided model and still get the error related to the checkpoint.

2019-06-21 07:06:36.239703: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BDGRU_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint

Python 2.7
Tensorflow 1.8.0

Thanks for your help in  advance.

**Comment by haotianteng** [comment]
for DNA basecalling please install from source, as the RNA basecalling uses a different model architecture thus break the backward compatibility of DNA basecalling in the release version.
