### ISSUE TITLE
Edit distance  Calculation

### ISSUE THREAD

**Issue by ardakdemir** [haotianteng/Chiron#91]
Is there a script to recalculate the edit distances you provide in the paper?
When we do the basecalling we only have access to the final aseemblies  and it is not possible to calculate the edit distance for each 300-length segment.

**Comment by haotianteng** [comment]
No there is no such script, but the segments' result is in the output/segment folder, it has the same format as the reads. You can use it to calculate the edit distance of the segment, however, it may require some customize coding as the segment is usually 10-20 base pairs long.
