### ISSUE TITLE
training data preparation

### ISSUE THREAD

**Issue by wxuzhang** [haotianteng/Chiron#92]
Hi,

I am trying to train a new model. When I am prepare the training data, I get the error:

:~/Documents/nanopore/demo/test$ chiron export -i trash -o output
('model_default_path', '/usr/local/lib/python2.7/dist-packages/chiron/model/DNA_default')
/home/wenxu/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
'read_start_rel_to_raw'
FAIL on trash/DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch16_read937_strand.fast5 file.   

Could you help on that?

**Comment by haotianteng** [comment]
For training purpose, the reads have to be labeled first using software like Tombo. Please refer to the training section on Chiron README.md
