### ISSUE TITLE
Cannot extract read_id attribute

### ISSUE THREAD

**Issue by ardakdemir** [haotianteng/Chiron#93]
I am trying to basecall the read.fast5 files provided under example_data/DNA using version 0.5.1. I get the following error : 

2019-08-17 01:18:04,902 ERROR Cannot extract file chiron/example_data/DNA/read5.fast5. "Can't open attribute (can't locate attribute: 'read_id')"

Should I update the fast5 files to include the read_id attribute or is there a way to sidestep this  using some other function then extract.py

Thanks!

**Comment by ardakdemir** [comment]
I checked the files and they are probably used for previous Chiron versions so I am closing this issue.

**Comment by dberma15** [comment]
Hi, could you clarify how this was resolved? The demo doesn't work with the files in DNA/read#.fast5 for me.
