### ISSUE TITLE
Assembly accuracy using racon

### ISSUE THREAD

**Issue by ardakdemir** [haotianteng/Chiron#94]
I am trying to calculate the assembly accuracy of the basecalling results of Chiron 0.5.1. 
I am using the racon_script provided to polish the genome. Yet Racon is not able to generate any sequences : 

[M::main::0.003*2.25] loaded/built the index for 0 target sequence(s)

However, when I run the same pipeline with basecalls from other basecallers, the same script successfully generates polishing results. 

Do you have any idea about the possible problem.

The code that calls Racon is as follows:

${RACON} ${out_file}merge_${i}_par.fastq ${out_file}mapping_${i}.paf ${out_file}raw_contigs_${i}.fasta >  ${out_file}consensus_${i}_0.fasta
 
One possible reason is that minimap generates a mapping_1.paf file which looks like it contains error: 

minimap2/minimap2  ${out_file}raw_contigs_${i}.fasta ${out_file}merge_${i}_par.fastq > ${out_file}mapping_${i}.paf

The above code generates a .paf file that looks like : 

ecoli_eval_0004	10478	5210	10267	+	utg000001l	12644	4	5138	413	5163	0	tp:A:S	cm:i:46	s1:i:387	dv:f:0.2403	rl:i:0
ecoli_eval_0024	12961	13	4323	+	utg000001l	12644	8117	12384	433	4362	0	tp:A:S	cm:i:45	s1:i:408	dv:f:0.2320	rl:i:0
ecoli_eval_0024	12961	11196	12914	+	utg000001l	12644	6374	8048	191	1727	0	tp:A:S	cm:i:20	s1:i:178	dv:f:0.2254	rl:i:0
ecoli_eval_0063	10149	486	3825	-	utg000002l	20147	3	3328	500	3399	0	tp:A:S	cm:i:58	s1:i:475	dv:f:0.1974	rl:i:0

Where you see that the final indices (i:0) all have 0.

A working example for .paf file looks like this:

4bd3fad0-cb87-4320-a741-7360907d7f4f	10978	4075	4230	-	utg000001l	43245	13121	13280	47	163	3	tp:A:P	cm:i:5	s1:i:44	s2:i:0	dv:f:0.1216	rl:i:44
518eb258-c7da-42a3-a1e2-fd71f42e2380	17489	10001	11293	-	utg000001l	43245	13265	14556	45	1292	5	tp:A:P	cm:i:5	s1:i:45	s2:i:0	dv:f:0.2550	rl:i:17
80c4c9f6-7461-4a88-9239-8d3cb7c479f5	31510	82	22374	+	utg000001l	43245	20556	42929	13536	22728	60	tp:A:P	cm:i:2355	s1:i:13392	s2:i:51	dv:f:0.0381	rl:i:23
80c4c9f6-7461-4a88-9239-8d3cb7c479f5	31510	28141	28304	-	utg000001l	43245	13118	13278	71	169	5	tp:A:P	cm:i:8	s1:i:68	s2:i:65	dv:f:0.0881	rl:i:23

Where the final indices have nonzero values

**Comment by ardakdemir** [comment]
I checked other mapping.paf files and they also contain i:0 so I dont think that is the issue.

Racon generates 0 target sequences when I run the following command 

racon read.fastq mapping.paf raw_contigs.fasta > consensus_0.fasta

Where I previously ran the command : ( for mapping)

minimap2 raw_contigs.fasta  read.fastq > mapping.paf

I would appreciate any help on why I am getting no sequences generated by racon

**Comment by haotianteng** [comment]
How is the result of the alignment of reads? I suppose this is a question related to Racon, maybe it's better to ask there.

**Comment by ardakdemir** [comment]
Dear @haotianteng,

Thank you for your reply. The problem is that racon successfully polishes reads from other basecallers so I thought it is more appropriate to ask this question here.

 I wonder if the error rate of the basecalls of chiron prevents racon from polishing the contigs. Have you ever observed such a case? If thats the case do you know a way to polish reads with high error rates?

**Comment by haotianteng** [comment]
What is your fast output, can you check if the base calling successfully done? Can you share me the fastq sample file? I can't give any help without sample. And from my test Chiron did a good job in assembly accuracy.

**Comment by haotianteng** [comment]
Can you share the SAM file or some sample fastq output files? Also, what is the setting you used to run Chiron? The batch size, the step, default parameters should work fine with the default model, but it would really help if you can share the command you used to run Chiron and also a sample output for me to figure out what is the problem.

**Comment by ardakdemir** [comment]
Apparently it was a problem related to the fastq file format. 
So after fixing my input to the racon it worked successfully.

Sorry not updating you on that.

Arda
