### ISSUE TITLE
Error when run base call step

### ISSUE THREAD

**Issue by adaxidedakaonang** [haotianteng/Chiron#96]
*Whern I run base call step, I get such error:*
 `AttributeError: 'Namespace' object has no attribute 'polya'`
*my command is :*
`python chiron/entry.py call -i input -o output -m model`
*input and model are folders which save fast5_file, model_file, respectively. Output is a empty folder.*

*the complete error is:*
`
Traceback (most recent call last):
  File "chiron/entry.py", line 154, in <module>
    main()
  File "chiron/entry.py", line 146, in main
    args.func(args)
  File "chiron/entry.py", line 38, in evaluation
    extract(FLAGS)
  File "/home/ubuntu/ADAXI/Gene/Chiron/chiron/utils/extract_sig_ref.py", line 61, in extract
    if FLAGS.polya is not None:
AttributeError: 'Namespace' object has no attribute 'polya'

`
*I use python2.7, tensorflow1.14*
**my package is:**

 packages in environment at /home/ubuntu/.conda/envs/chiron:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.8.0                    py27_0    defaults
astor                     0.8.0                    py27_0    defaults
backports                 1.0                        py_2    defaults
backports.weakref         1.0.post1                  py_1    defaults
biopython                 1.74                      <pip>
blas                      1.0                         mkl    defaults
c-ares                    1.15.0            h7b6447c_1001    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py27_0    defaults
chiron                    0.5.1                     <pip>
cudatoolkit               10.1.168                      0    defaults
cudnn                     7.6.0                cuda10.1_0    defaults
cupti                     10.1.168                      0    defaults
enum34                    1.1.6                    py27_1    defaults
funcsigs                  1.0.2                    py27_0    defaults
future                    0.17.1                   py27_0    defaults
futures                   3.3.0                    py27_0    defaults
gast                      0.3.2                      py_0    defaults
google-pasta              0.1.7                      py_0    defaults
grpcio                    1.16.1           py27hf8bcb03_1    defaults
h5py                      2.9.0            py27h7918eee_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
intel-openmp              2019.4                      243    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.9.2                hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
linecache2                1.0.0                    py27_0    defaults
markdown                  3.1.1                    py27_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.3.0            py27he904b0f_0    defaults
mkl_fft                   1.0.14           py27ha843d7b_0    defaults
mkl_random                1.1.0            py27hd6b4f25_0    defaults
mock                      3.0.5                    py27_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.16.5           py27h7e9f1db_0    defaults
numpy-base                1.16.5           py27hde5b4d6_0    defaults
openssl                   1.1.1d               h7b6447c_3    defaults
packaging                 19.2                      <pip>
pandas                    0.23.0                    <pip>
patsy                     0.5.1                     <pip>
pip                       19.3.1                   py27_0    defaults
protobuf                  3.9.2            py27he6710b0_0    defaults
pyparsing                 2.4.2                     <pip>
python                    2.7.17               h9bab390_0    defaults
python-dateutil           2.8.0                     <pip>
pytz                      2019.3                    <pip>
readline                  7.0                  h7b6447c_5    defaults
scipy                     1.2.1            py27h7c811a0_0    defaults
setuptools                41.4.0                   py27_0    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.30.0               h7b6447c_0    defaults
statsmodels               0.10.1                    <pip>
tensorboard               1.14.0           py27hf484d3e_0    defaults
tensorflow                1.14.0          gpu_py27h39f1c70_0    defaults
tensorflow-base           1.14.0          gpu_py27he45bfe2_0    defaults
tensorflow-estimator      1.14.0                     py_0    defaults
tensorflow-gpu            1.14.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py27_1    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.36.1                    <pip>
traceback2                1.4.0                    py27_0    defaults
unittest2                 1.1.0                    py27_0    defaults
werkzeug                  0.16.0                     py_0    defaults
wheel                     0.33.6                   py27_0    defaults
wrapt                     1.11.2           py27h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults

I need your help!Thanks!

**Comment by adaxidedakaonang** [comment]
I meet the same question when I run test step. It may be a python question, but I use python2.7 which is same version as yours.

**Comment by adaxidedakaonang** [comment]
When I change environment to py3 and tensorflow1.14, the mistake is still exits. 唉……

**Comment by haotianteng** [comment]
Fixed.
