### ISSUE TITLE
tensorflow - failed to call cuInit

### ISSUE THREAD

**Issue by lab-rat-kid** [haotianteng/Chiron#99]
After subdirectory processing I receive a number of lines from tensorflow, mostly information, but also these:
`2019-11-13 15:03:24.658577: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory`
`2019-11-13 15:03:24.658655: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)`
My first basecalling run is still running, but I'm not sure if these will effect the results.

**Comment by haotianteng** [comment]
Which version of Tensorflow did you install? This message indicate you haven't installed the CUDA library which is required by tf-gpu, so Tensorflow will run in CPU mode.

**Comment by haotianteng** [comment]
I will close it because of the inactivity, but you can commend if you still have a problem.
